### create
POST http://localhost:8080/api/review/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0RW1haWwiLCJpYXQiOjE2ODY0ODg2NjQsImV4cCI6MTY4NjQ5MjI2NH0.L-mitvsoQNe87mqZL2CkBqPlEIJG2bqgGOPG0RslCKs

    {
      "perfumeVitality": 3,
      "genderExpressionScale": 1,
      "seasons" : 3,
      "fashionStyle": 3,
      "description": "test",
      "perfumeId": 1
    }

###
POST http://localhost:8080/api/review/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0RW1haWwiLCJpYXQiOjE2ODY0ODg2NjQsImV4cCI6MTY4NjQ5MjI2NH0.L-mitvsoQNe87mqZL2CkBqPlEIJG2bqgGOPG0RslCKs

{
"perfumeVitality": 1,
"genderExpressionScale": 1,
"seasons" : 1,
"fashionStyle": 1,
"description": "test",
"perfumeId": 1
}

### Get
GET http://localhost:8080/api/review/get/1

### Get ALL
GET http://localhost:8080/api/review/getall/1

###
DELETE http://localhost:8080/api/review/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0RW1haWwiLCJpYXQiOjE2ODY0ODg2NjQsImV4cCI6MTY4NjQ5MjI2NH0.L-mitvsoQNe87mqZL2CkBqPlEIJG2bqgGOPG0RslCKs